# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "ec8aaa65c0fcb3f555298c414c008855"
application_url = "https://announcement-app-88ms.onrender.com"
embedded = true
name = "announcement-app"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_metaobjects,write_metaobject_definitions"

[metaobjects.app.example]
name = "Example"
description = "An example metaobject definition created by this template"

  [metaobjects.app.example.access]
  admin = "merchant_read_write"

[metaobjects.app.example.fields.title]
name = "Title"
type = "single_line_text_field"
required = true

[metaobjects.app.example.fields.description]
name = "Description"
type = "multi_line_text_field"

[webhooks]
api_version = "2026-07"

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/uninstalled"
  topics = [ "app/uninstalled" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/scopes_update"
  topics = [ "app/scopes_update" ]

[auth]
redirect_urls = [
  "https://announcement-app-88ms.onrender.com/api/auth"
]

[build]
automatically_update_urls_on_dev = true
